name:        cfgeq
version:     0.1.0.0
synopsis:    Unsound checker for CFG equality
description: Unsound checker for checking CFG equality on strings generated up
             to a specified length. Inefficient and unsound as it can only find
             counterexamples and not prove the lack of a longer counterexample.
category:    Validation
github:      chuahou/cfgeq
maintainer:  Chua Hou <human+github@chuahou.dev>

ghc-options:
    - -Wall
    - -fwarn-incomplete-uni-patterns
    - -fwarn-incomplete-record-updates
    - -static

default-extensions:
    - LambdaCase
    - TupleSections

dependencies:
    - base        >= 4.13 && < 5
    - containers ^>= 0.6.2.1
    - parsec     ^>= 3.1.14.0
    - mtl        ^>= 2.2.2

library:
    source-dirs: src

executable:
    main:         Main.hs
    source-dirs:  exe
    dependencies: cfgeq
    ghc-options:  -threaded

extra-doc-files:
    - README.md
    - CHANGELOG.md
