name: "Haddock to GitHub Pages"
on:
    pull_request:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2.3.4
        - uses: cachix/install-nix-action@v13
          with:
            install_url:      https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
            install_options:  '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
            extra_nix_config: experimental-features = nix-command flakes
        - uses: cachix/cachix-action@v10
          with:
            name:       chuahou
            authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        - name: Build Haddock documentation
          run: |
            nix develop -c cabal haddock --haddock-hyperlink-source
            cp dist-newstyle/build/x86_64-linux/ghc-*/cfgeq-*/doc/html/cfgeq -r docs
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@4.1.3
          with:
              branch: docs
              folder: docs
