name: "Draft release"
on:
    push:
        tags: v*

jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2.3.4
        - uses: cachix/install-nix-action@v13
          with:
            install_url:      https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
            install_options:  '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
            extra_nix_config: experimental-features = nix-command flakes
        - name: Get GHC/cabal versions
          id:   get-vers
          run: |
            export GHC_VER=$(nix develop -c sh -c \
                "ghc --version | awk '{ print \$NF }'")
            export CABAL_VER=$(nix develop -c sh -c \
                "cabal --version | head -n 1 | awk '{ print \$NF }'")
            echo "::set-output name=GHC_VER::${GHC_VER}"
            echo "::set-output name=CABAL_VER::${CABAL_VER}"
        - name: Setup GHC/cabal
          uses: haskell/actions/setup@v1
          with:
            ghc-version:   "${{ steps.get-vers.outputs.GHC_VER }}"
            cabal-version: "${{ steps.get-vers.outputs.CABAL_VER }}"
        - name: Build
          run: |
            mkdir -p artifacts
            cabal install
            cp $HOME/.cabal/bin/cfgeq \
                artifacts/cfgeq-$(echo ${{ github.ref }} | sed -n 's/.*\(v\([0-9]\.\)\{3\}[0-9]\)/\1/p')-${GITHUB_SHA}-linux
        - uses: actions/upload-artifact@v2
          with:
            name: artifacts-linux
            path: artifacts/cfgeq-*

    windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v2.3.4
        - name: Check tool versions
          run: |
              ghc --version
              cabal --version
        - name:  Build
          shell: cmd
          run: |
            mkdir artifacts
            cabal install
            cp %APPDATA%\cabal\bin\cfgeq.exe artifacts\cfgeq.exe
        - name:  Rename
          shell: bash
          run: |
            mv artifacts/cfgeq.exe \
                artifacts/cfgeq-$(echo ${{ github.ref }} | sed -n 's/.*\(v\([0-9]\.\)\{3\}[0-9]\)/\1/p')-${{ github.sha }}-windows.exe
        - uses: actions/upload-artifact@v2
          with:
            name: artifacts-windows
            path: artifacts\cfgeq-*

    release:
        runs-on: ubuntu-latest
        needs:   [linux, windows]
        steps:
        - uses: actions/checkout@v2.3.4
        - name: Parse changelog
          run: |
            TAG=$(echo ${{ github.ref }} | sed -n 's/.*\(\([0-9]\.\)\{3\}[0-9]\)/\1/p')
            sed "/^## ${TAG}/,/^##/!d; //d; /^$/d" CHANGELOG.md > CHANGES.md
        - uses: actions/download-artifact@v2
        - name: Draft release
          uses: ncipollo/release-action@v1
          with:
            draft:     true
            artifacts: "artifacts-linux/cfgeq-*,artifacts-windows/cfgeq-*.exe"
            bodyFile:  CHANGES.md
            token:     ${{ secrets.GITHUB_TOKEN }}
